### ISSUE TITLE
What is the reason that the parent must be a CoordinatorLayout or FrameLayout?

### ISSUE THREAD

**Issue by dvdciri** [bgogetap/StickyHeaders#15]
As per title, which one is the reason for that? It's a big limit for someone who want to use this library and i think that the library should be improved in order to remove that limit.

What do you think about that?

**Comment by bgogetap** [comment]
The way this library works is by attaching the view of the Sticky Header to the parent of the RecyclerView. To make positioning more predictable, I'm requiring FrameLayout/CoordinatorLayout  parents to allow me to assume the RecyclerView starts at (0,0) of the parent, and that any added view (i.e. the Sticky Header) will also be positioned at (0,0) in the parent. Some extra logic is performed if there is padding on the RecyclerView to make sure the header lines up, but that is trivial compared to the logic that would be needed to position the header correctly with no limitations on where the RecyclerView is used. 

All of these assumptions would be invalid if the RecyclerView's immediate parent was, for example, a LinearLayout.

While I agree it is a limitation, I'm curious as to how it's a big limitation for you. Is it not possible to nest your RecyclerView inside a FrameLayout?

This issue is fixable, and I may very well look into it in the future, though I can't say that it is a top priority. From the start my goal was to make this library as minimalistic on the positioning logic as possible.

**Comment by bgogetap** [comment]
This covers what I think #9 was alluding to. Closing #9 and continuing enhancement discussion in here.

**Comment by dvdciri** [comment]
Okay, now thst I know that, make more sense, I thought that the headers were directly attached to the RecyclerView and not to the parent.

I took a look into the code but not as deeper as I thought, but bdw I like this library because the implementation is really easy and customisable, and is really light as well.

About the parent limitation, it was just cause I need to add one more view to my view hierarchy apparently without any reasons. I thought, if it was really needed he could create a custom RecyclerView and extend in to a FrameLayour with your custom layout, that would be the same result but no one knows :)

**Comment by bgogetap** [comment]
That's a possibility (though I think there would be type issues that pop up for anything else you use with a RecyclerView), but then I would have to require users to use a custom "RecyclerView" as well as a custom LayoutManager. 

Like you pointed out, this library is very lightweight and involves minimal setup, both things that I would not like to lose in order to gain a marginal amount of flexibility.

**Comment by dvdciri** [comment]
In that case is up you, if you want i can give my contribution and create PR for that enhancement.

Just let me know if you consider that option.

**Comment by dvdciri** [comment]
If we can do it, without any "type" issues, for the developers that are going to implement it, it's even easier to use a custom component instead of adding one of those layout, asking himself why he should do that way, etc.. that's my thought.

**Comment by bgogetap** [comment]
I would be more than happy to look at a PR and possibly merge if we can keep it simple. 

Main thing that I think is vital is the custom RecyclerView must be a RecyclerView subclass. I'm not sure how you'd solve the whole abstracting the FrameLayout parent away without using a FrameLayout subclass that contains a RecyclerView. This is what I wouldn't want, since that custom view cannot be passed to any other objects that require a RecyclerView (i.e. ItemTouchHelper). Sure, you could put a getter on the custom FrameLayout to retrieve the inner RecyclerView, but that's just more friction added to using this library (this is an example of the "type" issues I was referring to).

**Comment by dvdciri** [comment]
Just thinking, if we use a charm RecyclerView, we could potential also remove the step of the layoutManager from the setup.. but then this is going to change the implementation of the library.

Think having a custom component means that you have to re-think about the implementation, if you want to keep everything the same and just fix that "limit" not sure if it's possible without adding some additional stuff. I'll take a look whenever I've got time.

**Comment by ppamorim** [comment]
What about SwipeRefreshLayout?

**Comment by bgogetap** [comment]
I'm pretty sure SwipeRefreshLayout can only host one direct child so this library would not work with it as the direct parent of the RecyclerView.

**Comment by bgogetap** [comment]
Closing this as I don't think this is a big limitation and any rework to make it compatible with all `ViewGroup`s would remove the simplicity that this library was meant to give.

I'll happy consider proposals to remove this requirement if anyone can think of one that wouldn't require any extra complexity.

**Comment by UMFsimke** [comment]
What about creating simple UI control that will be used instead of RecyclerView and that will actually be FrameLayout with RecyclerView inside of it? Control can expose basically few methods only. Such as `getRecyclerView()`. Generally speaking, its maybe even doable to move entire setup, adapter and layout manager to library but I guess that would be complex or more a long shot. I can create some code around it if that has any sense to you?

**Comment by bgogetap** [comment]
That's a possibility, however I see a few issues with it (issues with how "invasive" this library is, not issues that make your suggestion unfeasible).

Having a custom view handle the required wrapping of a RecyclerView in a view like a FrameLayout or CoordinatorLayout requires users to use that custom view in XML/Java. That's not a bad thing for a library to do when necessary, but it's something I tried very much to avoid when building this one. The FrameLayout/CoordinatorLayout parent requirement I still see as very minimal, considering most of the time that's probably the appropriate parent hosting a RecyclerView anyway. (Obvious exceptions would be when you have multiple RecyclerViews in a layout, similar to the PlayStore home page).

People do all sorts of crazy things with their adapters, or use adapters from other RecyclerView libraries that give them other benefits. If they were required to use one that, in any way, was tied to this library, that may impose limitations (or refactors for existing projects). 

To be honest, I want to find a way to go the other way (not even require the `StickyLayoutManager`), if possible. I haven't spent any time looking into that yet, but my ideal goal would be to have no custom components besides registering some sort of listener to a LayoutManager or something along those lines; along with, of course, the interfaces that are required for this library to work.

I'm actually really hoping this library becomes obsolete and Google officially adds support for sticky headers...but who knows how long that could take.

I appreciate your ideas and will definitely keep them in mind as I think of future improvements!
