### ISSUE TITLE
Header remains after setting a new adapter

### ISSUE THREAD

**Issue by chrisroe** [bgogetap/StickyHeaders#32]
I set a new adapter for my recyclerview, one that I do not intent to use sticky headers with, but the header still remains on top of the recyclerview. In this particular example I am using just one sticky header, so I do not know if this issue applies to other use cases as well.

Or is there a method to remove headers?

**Comment by chrisroe** [comment]
Nevermind, the issue was on my part.

**Comment by bgogetap** [comment]
I just made a quick test in the demo activity, toggling between building a list with headers and without, and everything works fine (setting a new adapter triggers the LayoutManager to re-layout children which updates the header positions in the library).

What is your `StickyHeaderHandler` and are you sure it is returning the updated dataset?

**Comment by chrisroe** [comment]
I made a simple demo activity myself right now and I was able to reproduce the issue.

I think I didnt make myself clear enough before, sorry about that.
My Recyclerview toggles between 2 adapters AND 2 LayoutManagers.
The first being the StickyHeaderManager obviously, the other being a simple LineaLayoutManager.
The first adapter uses StickyHeaders and implements the interface itself, the other doesnt. 
Both work perfectly fine, the only problem being the StickyHeader remaining on top of the other adapters items.

My RecyclerView is wrapped in a FrameLayout that is not the RootView of the Activity/Fragment.

Thank you for your help and time :)

**Comment by bgogetap** [comment]
Ok, I see. So since you're switching LayoutManagers as well, the StickyLayoutManager that bound the header is never receiving an updated call to layout children. 

I think the LayoutManager gets relevant enough callbacks for me to handle this automatically. Let me take a look later. Worst case, I can add a method to clear any bound headers, but hopefully this can be done without the need to manually call that.

Should have an update fixing this tonight or tomorrow afternoon.

**Comment by chrisroe** [comment]
Ok thank you :)

**Comment by bgogetap** [comment]
Fixed with ea872e2141da048037d2e2dc59a8bc683e739d09
