### ISSUE TITLE
Sticky header covers scrollbar and edge/glow effect

### ISSUE THREAD

**Issue by nitrico** [bgogetap/StickyHeaders#59]
Sticky header is drawn on top of edge/glow effect and also on top of scrollbar. Is there any way to avoid that?

**Comment by bgogetap** [comment]
The sticky header View is drawn on top of the RecyclerView, so there won't be any way to not obscure the scrollbar (at least that I can think of off the top of my head).

The edge glow effects shouldn't be obscured because there shouldn't be a sticky header if you're at the top of the list. I'll have to look into that and get back to you, but that should be how it works.

**Comment by bgogetap** [comment]
So, if the RecyclerView has no top padding and the first item is a StickyHeader, then I do see that it covers the edge effect since the first item is stickied.

I will see how difficult/reliable it would be to not sticky the first item if the RecyclerView is scrolled all the way to the top. Otherwise, adding at least 1dp padding to the top will fix this.

**Comment by bgogetap** [comment]
Well it appears this was actually pretty simple. Fix for the edge effect clipping coming in 0.5.0. 

I still think there is nothing I can do about the scrollbar being blocked by the header.

**Comment by bgogetap** [comment]
Released in 0.5.0
