### ISSUE TITLE
Support for NestedScrollView  

### ISSUE THREAD

**Issue by AntonyGolovin** [bgogetap/StickyHeaders#84]
Hi, thank you for the library. 

It would be great to make it work when RecyclerView is a child of NestedScrollView. `StickyLayoutManager.scrollVerticallyBy` is not getting called.

**Comment by SanjaGrgurevic** [comment]
@bgogetap can we get an ETA when NestedScrollView is going to get supported?

**Comment by bgogetap** [comment]
NestedScrollView can never be a direct parent because it only supports a single child View. This library adds the stickied header as another child to the parent of the RecyclerView.

As far as events getting passed down from a NestedScrollView through the FrameLayout then to the RecyclerView...I don't think there is anything in this library preventing that from working. If you have a simple repro app, I can take a look.

**Comment by bgogetap** [comment]
Closing due to no update. If you have a small app that repros the issue I can take a look.
